# Generated by Django 4.2.8 on 2023-12-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('purchased_from', models.CharField(max_length=50)),
                ('bill_no', models.CharField(max_length=10)),
                ('bill_amount', models.FloatField()),
                ('purchased_by', models.CharField(max_length=50)),
            ],
        ),
    ]
