# Generated by Django 4.2.8 on 2023-12-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0003_stockout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='item',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='IMSapp.items'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='item',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='IMSapp.items'),
        ),
    ]
