# Generated by Django 4.2.8 on 2023-12-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0004_alter_stockin_item_alter_stockout_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='out_by',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
